networks:
  web_net:
    name: web_net
    external: true

volumes:
  nexus_data:
    name: nexus_data
    external: false

services:
  nexus:
    image: sonatype/nexus3:${image_tag}
    container_name: nexus
    hostname: nexus
    restart: ${restart_policy}
    volumes:
      - nexus_data:/nexus-data
    environment:
      NEXUS_SECURITY_INITIAL_PASSWORD: ${nexus_admin_pass}
    networks:
      - web_net
