version: '3.8'

networks:
  app_network:
    name: app_network
    external: true
  galera-net:
    name: galera_net
    external: true

services:
  nginx:
    image: nginx:${IMAGE_TAG}
    container_name: nginx
    hostname: nginx
    restart: ${RESTART_POLICY}
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app_network
      - galera_net
