version: '3.8'

networks:
  app_network:
    name: app_network
    external: true
  galera-net:
    name: galera_net
    external: true

services:
  nginx:
    image: nginx:${IMAGE_TAG}
    container_name: nginx
    hostname: nginx
    restart: ${RESTART_POLICY}
    ports:
      - "80:80"
      - "3306:3306"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - .conf.d /etc/nginx/conf.d
    networks:
      - app_network
      - galera_net
    depends_on:
      - django_app1
      - django_app2
      - mariadb-node1
      - mariadb-node2
      - mariadb-node3
